### ISSUE TITLE
what's the purpose of '_split_A_hat' function?

### ISSUE THREAD

**Issue by pursueorigin** [xiangwang1223/neural_graph_collaborative_filtering#20]
I found you use '_split_A_hat' function to split the adjacency matrix into small blocks. But I am confused about it.
As for the memory overhead, this method still computes the representation of all nodes. Thus, it does not reduce the memory overhead.
As for the computation overhead, it also computes the representation of all nodes, even though one by one block. As a result, it also does not reduce the computation overhead.
So, what's the purpose of this function? Could you please give more explanation about this function? Thanks.

**Comment by Yindong-Zhang** [comment]
same question. hope for the answer.

**Comment by xiangwang1223** [comment]
Hi, thanks for your interests! Sorry for the late reply after a busy week.
1. Such a function was designed to reduce memory usage in my first try. I keep it in the first version to show (or more precisely, record) what attempts we have tried, while it seems to be not that useful.
2. I think that you can simply set the n_fold to '1' or just ignore such function.

Thanks.

**Comment by Yindong-Zhang** [comment]
thanks for the answer. good job!

**Comment by pursueorigin** [comment]
Thanks.
