### ISSUE TITLE
GCN Embedding Initialization Conflicts

### ISSUE THREAD

**Issue by voladorlu** [xiangwang1223/neural_graph_collaborative_filtering#3]
@xiangwang1223  Please check this out. For initializing embeddings with gcn and gcmc, they use the same initializer.

`        if self.alg_type in ['ngcf']:
            self.ua_embeddings, self.ia_embeddings = self._create_ngcf_embed()

        elif self.alg_type in ['gcn']:
            self.ua_embeddings, self.ia_embeddings = self._create_gcmc_embed()

        elif self.alg_type in ['gcmc']:
            self.ua_embeddings, self.ia_embeddings = self._create_gcmc_embed()`

**Comment by xiangwang1223** [comment]
thanks a lot@voladorlu. I have fixed the bug.
