### ISSUE TITLE
error：when adj_mat[:n_users, n_users:] = R

### ISSUE THREAD

**Issue by gumanchang** [xiangwang1223/neural_graph_collaborative_filtering#5]
adj_mat[:n_users, n_users:] = R
  File "/data/anaconda2/lib/python2.7/site-packages/scipy/sparse/lil.py", line 366, in __setitem__
    x = x.toarray()
  File "/data/anaconda2/lib/python2.7/site-packages/scipy/sparse/lil.py", line 443, in toarray
    d = self._process_toarray_args(order, out)
  File "/data/anaconda2/lib/python2.7/site-packages/scipy/sparse/base.py", line 1130, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
MemoryError

how to solve adj_mat problem when user and item is huge number ?

**Comment by xiangwang1223** [comment]
Hi, I have used the sparse matrix in scipy to reduce the memory. I saw the error showing `x=x.toarray()`, so did you convert the sparse matrix to the dense?

BTW, may I know which dataset you use?

**Comment by gumanchang** [comment]
hi,  i think it caused by R.tolil() which convert the sparse matrix to array. when use gowalla dataset it works, But it when meet real world dataset it fail. So how to solve it, or does it can be simply bypass? :)

**Comment by xiangwang1223** [comment]
Hi, we have tried the robustness of our model. It should be fine with the adjacency matrix with ~0.1 million nodes and ~3 million nonzero entries. One solution is to implement the model in mini-batch fashion, that is, sampling k one-hop neighbors each time, rather than the whole Laplacian matrix. Thanks.
