### ISSUE TITLE
How can you improve the efficiency of this situation

### ISSUE THREAD

**Issue by Lx1010** [xiangwang1223/neural_graph_collaborative_filtering#9]
hello，I'm trying this kind of dataset，eg：300users，10000items。A user is connected to at least one item，An item must be connected to only one user。so，This bipartite graph only has 10,000 edges and it is  an unconnected graphs。In other words，each user is a small Subconnected Graph.
i think this graph only have one-order connectivity. I have tried this situation on one embedding propagation layer and tuning it with your code，but it could not worked very well。 
So,Why are the results not good with this situation？ and How can I improve it.
thank you

**Comment by xiangwang1223** [comment]
Hi, I think you can explore it by yourself. Thanks.
